<style type="text/css"<?php echo $this->nonceAttr; ?>><?php
	include_once(__DIR__ . '/refresh.panel.css');
?></style>
<div class="tracy-panel-refresh">
	<h1>
		<span class="left">Refresh Panel</span>
		<span class="right">active refreshing pages: <span>unknown</span></span>
	</h1>
	<div class="content" id="tracy-refresh-panel-content-<?php echo $this->panelUniqueId; ?>">
		<form action="#" method="post"><?php
				$locationsId = "tracy-refresh-panel-locations-{$this->panelUniqueId}";
				$excludesId = "tracy-refresh-panel-excludes-{$this->panelUniqueId}";
				$extensionId = "tracy-refresh-panel-extension-{$this->panelUniqueId}-";
			?><fieldset>
				<legend>Settings</legend>
				<label class="block" for="<?php echo $locationsId; ?>">
					Directories: <br />
					<i>(one directory can't contain other)</i>
				</label>
				<textarea id="<?php echo $locationsId; ?>" name="locations"></textarea>
				<label class="block" for="<?php echo $excludesId; ?>">
					Excludes: <br />
					<i>(JS RegExp or path, `~` in path will be replaced with app root)</i>
				</label>
				<textarea id="<?php echo $excludesId; ?>" name="excludes"></textarea>
				<label class="block">
					Extensions: <br />
					<i>(include only extensions bellow, no options means `include any extension`)</i>
				</label>
				<div class="checkbox-groups">
					<?php foreach ($this->defaultExtensions as $defaultExtensionsGroup): ?>
						<div class="checkbox-group">
							<?php foreach ($defaultExtensionsGroup as $defaultExtension): ?>
								<div class="checkbox">
									<input 
										id="<?php echo $extensionId . $defaultExtension; ?>" 
										type="checkbox" 
										name="extensions"
										value="<?php echo $defaultExtension; ?>" 
										checked="checked" />
									<label 
										class="checkbox" 
										for="<?php
											echo $extensionId . $defaultExtension;
										?>">*.<?php echo $defaultExtension; ?></label>
								</div>
							<?php endforeach; ?>
						</div>
					<?php endforeach; ?>
				</div>
				<hr />
				<button name="start" class="passive"></button>
				<i class="status"></i>
			</fieldset>
		</form>
	</div>
	<?php echo $this->debugCode; ?>
</div>