<span class="tracy-tab-refresh"  id="tracy-refresh-panel-tab-<?php echo $this->panelUniqueId; ?>" title="Panel to show automatic page refreshing">
	<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
		 viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
		<style type="text/css">
			circle.passive{fill:#AAAAAA;}
			circle.active{fill:#104D9E;}
			#tracy-debug-bar > ul > li > a[rel=tracy-debug-panel-refresh-panel]{padding:0 0.1em 0 0.3em;}
		</style>
		<circle class="passive" cx="8" cy="8" r="8"/>
		<path fill="#ffffff" d="M9.8,10.5c-1.2,1.2-3.1,1.2-4.2,0C5,9.9,4.6,9.2,4.6,8.4S5,6.8,5.5,6.2c0.6-0.6,1.3-0.9,2.1-0.9
			s1.6,0.3,2.1,0.9c0,0,0,0,0,0L8.4,7.6l5,0.7l-0.7-5l-1.4,1.4c0,0,0,0,0,0C10.2,3.9,9,3.4,7.6,3.4c-1.3,0-2.6,0.5-3.5,1.5
			C3.2,5.8,2.6,7,2.6,8.4c0,1.3,0.5,2.6,1.5,3.5c1,1,2.3,1.5,3.5,1.5s2.6-0.5,3.5-1.5c0.1-0.1,0.2-0.3,0.3-0.4l-1.4-1.4
			C10,10.2,9.9,10.4,9.8,10.5z"/>
	</svg>
	<span class="tracy-label"></span>
</span>
<script type="text/javascript"<?php echo $this->nonceAttr; ?>>
	var Tracy = window.Tracy || {};
	Tracy.DebugRefreshPanel = (function(){
		<?php include_once(__DIR__ . '/js/Client.js'); echo PHP_EOL; ?>
		return DebugRefreshPanel;
	})();
	Tracy.DebugRefreshPanel.GetInstance(<?php echo \MvcCore\Tool::JsonEncode([
		'panelUniqueId'			=> $this->panelUniqueId,
		'panelId'				=> $this->getId(),
		'port'					=> $this->port,
		'appRoot'				=> $this->appRoot,
		'defaultLocations'		=> $this->defaultLocations,
		'defaultEcludePatterns' => $this->defaultEcludePatterns,
		'defaultExtensions'		=> $this->defaultExtensions,
		'startMonitoringParam'	=> static::$xhrStartMonitoringParamName,
	]); ?>);
</script>